# Generated by Django 2.2.16 on 2020-09-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(max_length=10),
        ),
    ]
